require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_catagories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductCatagory. As you add validations to ProductCatagory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductCatagory.create! valid_attributes
      get product_catagories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_catagory = ProductCatagory.create! valid_attributes
      get product_catagory_url(product_catagory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_catagory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product_catagory = ProductCatagory.create! valid_attributes
      get edit_product_catagory_url(product_catagory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductCatagory" do
        expect {
          post product_catagories_url, params: { product_catagory: valid_attributes }
        }.to change(ProductCatagory, :count).by(1)
      end

      it "redirects to the created product_catagory" do
        post product_catagories_url, params: { product_catagory: valid_attributes }
        expect(response).to redirect_to(product_catagory_url(ProductCatagory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductCatagory" do
        expect {
          post product_catagories_url, params: { product_catagory: invalid_attributes }
        }.to change(ProductCatagory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_catagories_url, params: { product_catagory: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested product_catagory" do
        product_catagory = ProductCatagory.create! valid_attributes
        patch product_catagory_url(product_catagory), params: { product_catagory: new_attributes }
        product_catagory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the product_catagory" do
        product_catagory = ProductCatagory.create! valid_attributes
        patch product_catagory_url(product_catagory), params: { product_catagory: new_attributes }
        product_catagory.reload
        expect(response).to redirect_to(product_catagory_url(product_catagory))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_catagory = ProductCatagory.create! valid_attributes
        patch product_catagory_url(product_catagory), params: { product_catagory: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_catagory" do
      product_catagory = ProductCatagory.create! valid_attributes
      expect {
        delete product_catagory_url(product_catagory)
      }.to change(ProductCatagory, :count).by(-1)
    end

    it "redirects to the product_catagories list" do
      product_catagory = ProductCatagory.create! valid_attributes
      delete product_catagory_url(product_catagory)
      expect(response).to redirect_to(product_catagories_url)
    end
  end
end
